apiVersion: "v1"
kind: "Pod"
metadata:
spec:
  containers:
  - command:
    - "jenkins-agent"
    image: "utilitynode"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "persist-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - name: "maven"
    image: "maven:3.6.0-jdk-8-alpine"
    imagePullPolicy: "IfNotPresent"
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "persist-volume"
      readOnly: false
    - mountPath: "/root/.m2"
      name: "maven-volume"
      readOnly: false
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  volumes:    
  - name: "persist-volume"
    persistentVolumeClaim:
      claimName: jenkins-slave-fin-test-pvc
  - name: "maven-volume"
    persistentVolumeClaim:
      claimName: maven-fin-test-pvc
